### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by ghost** [borodar/first-site#1]
Dear friend, 

you definitely need to add new features and **update** you website. I would recommend you to add:
* Bio 
* Contact form
* Animations
* Some interactivity

---

Check out [freeCodeCamp](https://freecodecamp.org) , if you want to learn new stuff

**Comment by oleksssandr** [comment]
> 
> 
> Dear friend,
> 
> you definitely need to add new features and **update** you website. I would recommend you to add:
> 
>     * Bio
> 
>     * Contact form
> 
>     * Animations
> 
>     * Some interactivity
> 
> 
> Check out [freeCodeCamp](https://freecodecamp.org) , if you want to learn new stuff
